contact:
  name: nila
  email: nila@test.com
  address:
    line: 1, some place
    postcode: rg40
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#---
#spring:
#  profiles:
#    active:
#---
#spring:
#  config:
#    activate:
#      on-profile: